language: python
sudo: required
dist: trusty
install:
  - wget https://root.cern.ch/download/root_v6.06.06.Linux-ubuntu14-x86_64-gcc4.8.tar.gz
  - tar -xzf root_v6.06.06.Linux-ubuntu14-x86_64-gcc4.8.tar.gz
  - . root/bin/thisroot.sh
  - HOME=`pwd`
  - touch ~/.bashrc
  - ./install.sh
  - . ~/.bashrc
script:
  crombie test
