#! /bin/bash

# Kills all 'crombie squid jobs',
# cleans up current output directory, and
# removes unfinished files from submission queue

if [ ! -f CrombieSlimmingConfig.sh ]
then

    echo "CrombieSlimmingConfig.sh does not exist. Don't run from this directory"
    exit 1

fi

# Stop jobs
condor_rm $USER

# Remove new jobs from submission queue
echo "DELETE FROM queue WHERE status != 'finished';" | mysql --defaults-file=$HOME/my.cnf --defaults-group-suffix=-submit -Dsubmit_queue

# Remove the placeholder files generated by condor
source CrombieSlimmingConfig.sh

if [ -d "$CrombieOutDir" ]
then

    echo "Removing $CrombieOutDir in 3 seconds"
    sleep 3
    rm -r "$CrombieOutDir"
    echo "Done"

fi
